export default {
  'plugin-viewport': 'Viewport',
  'plugin-scroll': 'Scroll',
  'plugin-render': 'Render',
  'plugin-tiling': 'Tiling',
  'plugin-thumbnail': 'Thumbnail',
  'plugin-zoom': 'Zoom',
  'plugin-rotate': 'Rotate',
  'plugin-selection': 'Selection',
  'plugin-capture': 'Capture',
  'plugin-print': 'Print',
  'plugin-export': 'Export',
  'plugin-spread': 'Spread',
  'plugin-pan': 'Pan',
}
